Repository CS3219-AY2324S1/ay2324s1-course-assessment-g27, pull requests merged in 2023-10, with the labels that each got.

#30 Edit question pages for admin and users
  assignment/assignment1/client/src/scenes/loginPage/Form.tsx
  assignment/assignment1/client/src/scenes/navBar/index.tsx
  assignment/assignment1/client/src/scenes/widgets/AddQuestionForm.css
  assignment/assignment1/client/src/scenes/widgets/AddQuestionForm.tsx
  assignment/assignment1/client/src/scenes/widgets/FormComponent.css
  assignment/assignment1/client/src/scenes/widgets/FormComponent.tsx
  assignment/assignment1/client/src/scenes/widgets/MyQuestionWidget.tsx
  assignment/assignment1/client/src/state/user.ts
  assignment/assignment1/server/src/controllers/auth.ts
  assignment/assignment1/server/src/controllers/dbConnection.ts
  assignment/assignment1/server/src/dbSeed.ts
  assignment/assignment1/server/src/models/User.ts
Labels: assignment

#34 cleaned up code a little, corrected a typo in import and added random question selection for the room creation
  assignment/assignment1/client/src/scenes/homePage/homePage.tsx
  assignment/assignment1/client/src/scenes/roomPage/confirmationPopup.css
  assignment/assignment1/client/src/scenes/roomPage/confirmationPopup.tsx
  assignment/assignment1/client/src/scenes/roomPage/roomPage.css
  assignment/assignment1/client/src/scenes/roomPage/roomPage.tsx
Labels: feature- Must have

#32 Revamp Question Service UI for Add, Edit and Display Form
  assignment/assignment1/client/src/scenes/widgets/AddQuestionForm.tsx
  assignment/assignment1/client/src/scenes/widgets/DisplayDescriptionForm.tsx
  assignment/assignment1/client/src/scenes/widgets/DisplayQuestionInformation.tsx
  assignment/assignment1/client/src/scenes/widgets/MyQuestionWidget.tsx
  assignment/assignment1/client/src/scenes/widgets/QuestionFields/ConstraintsFields.tsx
  assignment/assignment1/client/src/scenes/widgets/QuestionFields/ExampleFields.tsx
  assignment/assignment1/client/src/scenes/widgets/QuestionFields/QuestionFieldsFormUI.tsx
  assignment/assignment1/client/src/scenes/widgets/editQuestionPopup.tsx
  assignment/assignment1/client/src/state/question.ts
  assignment/assignment1/server/src/models/Question.ts
Labels: enhancement

#31 Added profile page
  assignment/assignment1/client/package-lock.json
  assignment/assignment1/client/package.json
  assignment/assignment1/client/src/App.css
  assignment/assignment1/client/src/App.tsx
  assignment/assignment1/client/src/api/usersAPI/changePwdById.ts
  assignment/assignment1/client/src/api/usersAPI/comparePwd.ts
  assignment/assignment1/client/src/api/usersAPI/deleteUserById.ts
  assignment/assignment1/client/src/api/usersAPI/editUserById.ts
  assignment/assignment1/client/src/api/usersAPI/getUserById.ts
  assignment/assignment1/client/src/scenes/changePwdPage/ChangePwdPage.css
  assignment/assignment1/client/src/scenes/changePwdPage/ChangePwdPage.tsx
  assignment/assignment1/client/src/scenes/changePwdPage/PwdForm.css
  assignment/assignment1/client/src/scenes/changePwdPage/PwdForm.tsx
  assignment/assignment1/client/src/scenes/navBar/index.tsx
  assignment/assignment1/client/src/scenes/profilePage/Form.tsx
  assignment/assignment1/client/src/scenes/profilePage/ProfilePage.css
  assignment/assignment1/client/src/scenes/profilePage/ProfilePage.tsx
  assignment/assignment1/client/src/scenes/profilePage/components/Account.css
  assignment/assignment1/client/src/scenes/profilePage/components/Account.tsx
  assignment/assignment1/client/src/scenes/profilePage/components/BasicInfo.css
  assignment/assignment1/client/src/scenes/profilePage/components/BasicInfo.tsx
  assignment/assignment1/client/src/scenes/profilePage/components/DeleteUserPopup.css
  assignment/assignment1/client/src/scenes/profilePage/components/DeleteUserPopup.tsx
  assignment/assignment1/client/src/scenes/profilePage/components/UserLeftBar.css
  assignment/assignment1/client/src/scenes/profilePage/components/UserLeftBar.tsx
  assignment/assignment1/client/src/scenes/widgets/MyQuestionWidget.tsx
  assignment/assignment1/client/src/scenes/widgets/UserWidget.tsx
  assignment/assignment1/client/src/state/index.ts
  assignment/assignment1/client/src/state/user.ts
  assignment/assignment1/server/package-lock.json
  assignment/assignment1/server/package.json
  assignment/assignment1/server/src/controllers/auth.ts
  assignment/assignment1/server/src/controllers/users.ts
  assignment/assignment1/server/src/dbSeed.ts
  assignment/assignment1/server/src/middleware/auth.ts
  assignment/assignment1/server/src/models/Queries.ts
  assignment/assignment1/server/src/models/User.ts
  assignment/assignment1/server/src/routes/auth.ts
  assignment/assignment1/server/src/routes/users.ts
Labels: assignment

#53 add error handling in question service for title
  assignment/assignment1/client/src/api/questionAPI/createQuestion.ts
  assignment/assignment1/client/src/api/questionAPI/editQuestion.ts
  assignment/assignment1/client/src/scenes/widgets/AddQuestionForm.tsx
  assignment/assignment1/client/src/scenes/widgets/MyQuestionWidget.tsx
  assignment/assignment1/client/src/scenes/widgets/editQuestionPopup.tsx
  assignment/assignment1/server/src/controllers/questions.ts
  assignment/assignment1/server/src/models/Question.ts
Labels: bug, enhancement, assignment

#67 [WIP] Update UI for auth page
  assignment/assignment1/client/index.html
  assignment/assignment1/client/src/api/usersAPI/registerUser.ts
  assignment/assignment1/client/src/assets/loginPage.png
  assignment/assignment1/client/src/assets/react.svg
  assignment/assignment1/client/src/components/TopBar.tsx
  assignment/assignment1/client/src/index.css
  assignment/assignment1/client/src/scenes/loginPage/Form.tsx
  assignment/assignment1/client/src/scenes/loginPage/LoginPage.css
  assignment/assignment1/client/src/scenes/loginPage/LoginPage.tsx
  assignment/assignment1/client/src/theme.ts
Labels: enhancement

#73 Matching service UI and rabbitMQ
  assignment/assignment1/client/package-lock.json
  assignment/assignment1/client/package.json
  assignment/assignment1/client/src/api/questionAPI/getQuestion.ts
  assignment/assignment1/client/src/api/roomAPI.ts
  assignment/assignment1/client/src/scenes/homePage/homePage.tsx
  assignment/assignment1/client/src/scenes/homePage/matchLoadingPage.css
  assignment/assignment1/client/src/scenes/homePage/matchLoadingPage.tsx
  assignment/assignment1/client/src/scenes/qnsHistPage/QnsHistPage.tsx
  assignment/assignment1/client/src/scenes/roomPage/roomPage.tsx
  assignment/assignment1/client/src/scenes/widgets/DisplayQuestionInformation.css
  assignment/assignment1/client/src/scenes/widgets/DisplayQuestionInformation.tsx
  assignment/assignment1/client/src/scenes/widgets/MyQuestionWidget.tsx
  assignment/assignment1/client/src/scenes/widgets/editQuestionPopup.tsx
  assignment/assignment1/client/src/state/room.ts
  assignment/assignment1/server/package-lock.json
  assignment/assignment1/server/package.json
  assignment/assignment1/server/src/controllers/queue.ts
  assignment/assignment1/server/src/controllers/rooms.ts
  assignment/assignment1/server/src/controllers/socketIo.ts
  assignment/assignment1/server/src/index.ts
  assignment/assignment1/server/src/models/MatchProcess.ts
  assignment/assignment1/server/src/models/Question.ts
  assignment/assignment1/server/src/models/Room.ts
  assignment/assignment1/server/src/routes/rooms.ts
  assignment/assignment1/server/src/util/constant.ts
  assignment/assignment1/server/yarn.lock
Labels: feature- Must have

#78 Fix on Question Service Backend and Frontend
  assignment/assignment1/client/package-lock.json
  assignment/assignment1/client/package.json
  assignment/assignment1/client/src/scenes/widgets/DisplayQuestionInformation.tsx
  assignment/assignment1/client/src/scenes/widgets/MyQuestionWidget.css
  assignment/assignment1/client/src/scenes/widgets/MyQuestionWidget.tsx
  assignment/assignment1/client/yarn.lock
  assignment/assignment1/server/src/controllers/auth.ts
  assignment/assignment1/server/src/middleware/auth.ts
  assignment/assignment1/server/src/routes/questions.ts
Labels: enhancement

#81 Add match with programming language and fix matching logic error
  assignment/assignment1/client/package-lock.json
  assignment/assignment1/client/package.json
  assignment/assignment1/client/src/constants/constants.ts
  assignment/assignment1/client/src/scenes/homePage/homePage.css
  assignment/assignment1/client/src/scenes/homePage/homePage.tsx
  assignment/assignment1/client/src/scenes/roomPage/editor.tsx
  assignment/assignment1/client/src/scenes/roomPage/roomPage.tsx
  assignment/assignment1/client/src/scenes/widgets/DisplayQuestionInformation.tsx
  assignment/assignment1/client/src/state/room.ts
  assignment/assignment1/client/yarn.lock
  assignment/assignment1/server/src/api/questionApi.ts
  assignment/assignment1/server/src/api/roomApi.ts
  assignment/assignment1/server/src/controllers/queue.ts
  assignment/assignment1/server/src/controllers/rooms.ts
  assignment/assignment1/server/src/controllers/socketIo.ts
  assignment/assignment1/server/src/models/Room.ts
Labels: bug, enhancement
