Repository CS3219-AY2324S1/ay2324s1-course-assessment-g27, pull requests merged in 2023-09, with the labels that each got.

#9 Set up Backend for Assignment 1
  assignment/assignment1/client/src/scenes/loginPage/LoginPage.css
  assignment/assignment1/client/src/scenes/loginPage/LoginPage.tsx
  assignment/assignment1/client/src/scenes/questionPage/QuestionPage.css
  assignment/assignment1/client/src/scenes/questionPage/QuestionPage.tsx
  assignment/assignment1/client/src/scenes/widgets/AddQuestionForm.tsx
  assignment/assignment1/client/src/test.tsx
  assignment/assignment1/server/.env-sample
  assignment/assignment1/server/.gitignore
  assignment/assignment1/server/package-lock.json
  assignment/assignment1/server/package.json
  assignment/assignment1/server/src/controllers/auth.ts
  assignment/assignment1/server/src/controllers/questions.ts
  assignment/assignment1/server/src/controllers/users.ts
  assignment/assignment1/server/src/data/index.ts
  assignment/assignment1/server/src/index.ts
  assignment/assignment1/server/src/middleware/auth.ts
  assignment/assignment1/server/src/models/Question.ts
  assignment/assignment1/server/src/models/User.ts
  assignment/assignment1/server/src/routes/auth.ts
  assignment/assignment1/server/src/routes/questions.ts
  assignment/assignment1/server/src/routes/users.ts
  assignment/assignment1/server/tsconfig.json
Labels: assignment

#21 Fix registering issues
  assignment/assignment1/client/src/scenes/loginPage/Form.tsx
  assignment/assignment1/server/package-lock.json
  assignment/assignment1/server/package.json
Labels: bug

#22 Fix question page username return null issues
  assignment/assignment1/client/src/scenes/loginPage/Form.tsx
  assignment/assignment1/client/src/scenes/questionPage/QuestionPage.tsx
Labels: bug

#23 Assignment2b
  assignment/assignment 2/readme.md
  assignment/assignment 2/src/index.js
  assignment/assignment1/.gitignore
  assignment/assignment1/client/package-lock.json
  assignment/assignment1/client/package.json
  assignment/assignment1/client/src/api/config.ts
  assignment/assignment1/client/src/api/questionAPI/createQuestion.ts
  assignment/assignment1/client/src/api/questionAPI/deleteQuestion.ts
  assignment/assignment1/client/src/api/questionAPI/editQuestion.ts
  assignment/assignment1/client/src/api/questionAPI/getQuestion.ts
  assignment/assignment1/client/src/scenes/questionPage/QuestionPage.tsx
  assignment/assignment1/client/src/scenes/widgets/MyQuestionWidget.tsx
  assignment/assignment1/client/src/scenes/widgets/editQuestionPopup.tsx
  assignment/assignment1/client/src/state/question.ts
  assignment/assignment1/server/src/controllers/questions.ts
  assignment/assignment1/server/src/index.ts
  assignment/assignment1/server/src/routes/questions.ts
Labels: assignment

#25 Refined UI and refactored code
  assignment/assignment1/client/src/api/questionAPI/createQuestion.ts
  assignment/assignment1/client/src/scenes/navBar/index.tsx
  assignment/assignment1/client/src/scenes/widgets/DisplayDescriptionForm.tsx
  assignment/assignment1/client/src/scenes/widgets/MyQuestionWidget.css
  assignment/assignment1/client/src/scenes/widgets/MyQuestionWidget.tsx
  assignment/assignment1/client/src/scenes/widgets/editQuestionPopup.tsx
Labels: enhancement
